version: '3.9'

services:
  db-postgres:
    image: postgres:latest
    container_name: db-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
    ports:
      - "5432:5432"
